Metatavu/ikioma-dh-integration-spec

swagger.yaml
=> Added appointment description

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/6
=> practitioners api

swagger.yaml
=> Feature 8 appointments

swagger.yaml
=> Fix for incorrect date time format in Appointment response

swagger.yaml
Changed spelling from speciality to specialty
Resolves: #14
=> Added missing ID fields to Appointment object

swagger.yaml
=> Changed API to use keycloak user ID instead of encrypted SSN

swagger.yaml
=> Feature 16 reserve appointments

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/20
=> added create patiend endpoint

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/22
=> added patient exsits endpoint

swagger.yaml
=> Added spec for prescriptions

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/28
=> added return body to patient creation

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/30
=> init spec version for booking patient arrivals

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/33
=> added update patient endpoint

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/32
=> added endpoint for retrieving vaccinations and vaccination object

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/39
=> added data permissions fields

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/43
=> returned employer id to the patient definition

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/45
=> removed web code from required appointment object properties

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/47
=> Feature 47 appointment more fields

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/49
=> practitioners renewing prescriptions endpoint

swagger.yaml
Resolves https://github.com/Metatavu/ikioma-dh-integration-spec/issues/51
=> added id field to prescription practitioner object

swagger.yaml
=> Added support for available dates
